// <auto-generated />
namespace ChallengeBoard.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class LogoUrl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LogoUrl));
        
        string IMigrationMetadata.Id
        {
            get { return "201304152258388_LogoUrl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
