// <auto-generated />
namespace ChallengeBoard.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddCompetitorJoin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCompetitorJoin));
        
        string IMigrationMetadata.Id
        {
            get { return "201302132357248_AddCompetitorJoin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
