// <auto-generated />
namespace ChallengeBoard.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class EstimatedRatings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EstimatedRatings));
        
        string IMigrationMetadata.Id
        {
            get { return "201305012246273_EstimatedRatings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
